### ISSUE TITLE
Have modified text be same color as unmodified

### ISSUE THREAD

**Issue by rmtuckerphx** [speechmarkdown/speechmarkdown-vscode#1]
The format for modified text is: (text)[modifiers]
Is there a way for "text" to be the same color as other text in the sentence so that it is easy to read the sentence by following the color. The parenthesis and square brackets would remain white.

Underlined text would be the same color as rest of the text in the sentence:
![image](https://user-images.githubusercontent.com/247472/74626534-2d9e5f80-510d-11ea-9fdf-44418e452c9e.png)

**Comment by johniwasz** [comment]
Yes, that can be addressed with an update to the syntax definition. Is this what you had in mind?

![smdupdate01](https://user-images.githubusercontent.com/44126651/74694273-888f8f80-51bd-11ea-8724-d383cfdf2096.png)

**Comment by johniwasz** [comment]
This update has been pushed out in version 0.0.3.

**Comment by rmtuckerphx** [comment]
Perfect! Thank you
