### ISSUE TITLE
Add Completion Providers

### ISSUE THREAD

**Issue by rmtuckerphx** [speechmarkdown/speechmarkdown-vscode#2]
Is it possible to trigger a snippet when the developer types close parenthesis + open square bracket: ")[" ?
That is key combination that should be reliable in determining Speech Markdown.

C0mbinations include:
- )[    (close parenthesis + open square bracket) - text modifier start
- #[    (number + open square bracket) - section start
- ![     (exclamation +  open square bracket) - audio tag start

**Comment by johniwasz** [comment]
Not though snippets, but there is a code completion interface that can be implemented.

**Comment by johniwasz** [comment]
IntelliSense and auto-completion has been added to the latest version, 0.0.6.

By default Visual Studio Code does not provide IntelliSense handling in strings. For more information, please see:

[TS/JS Path Quick Suggestion IntelliSense Does Not Work Unless QuickSuggestions.strings is enabled #23962](https://github.com/microsoft/vscode/issues/23962)

**NOTE:** IntelliSense in strings is _not_ available in JSON or YAML. If you wish to use Intellisense
in JSON files you can temporarily change the file extension to _js_.

If you wish to enabled IntelliSense in strings, then apply the following settings to your project folder.

1. Create a .vscode folder
2. Ad the following settings a new settings.json file:

```json
 "editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": true
  }
```
![intellisense01](https://user-images.githubusercontent.com/44126651/87233961-4f3d0380-c39a-11ea-8322-81faaede325a.gif)

Typing any of the following and using ctrl+space will trigger suggestions:

- #[
- (sometext)[
- [
- ; (when used within the brackets of the samples above)

**NOTE:** The audio tag !['{link to audio file}'] doesn't have any additional internal tags and so the auto-completion provider does not have any additional text to display.
