### ISSUE TITLE
Audio and Section formatting

### ISSUE THREAD

**Issue by rmtuckerphx** [speechmarkdown/speechmarkdown-vscode#3]
Can we also color white the "!" at the beginning of the audio tag and the "#" that is part of the section?
Also, strangely, the word "audio" in the filename in the audio markdown is yellow not white like it should be.

![image](https://user-images.githubusercontent.com/247472/75087041-a3813d00-54f8-11ea-93be-f5d49622eae3.png)

**Comment by johniwasz** [comment]
This is resolved as of the latest 0.4.0 update.

There is a separate outstanding issue with the sub tag. Supporting that is raising some regular expression challenges.
